name: gains_and_guide
description: A new Flutter project for weight training routine management and AI coaching.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  
  # Local Database
  sqflite: 2.3.3+2
  path: ^1.8.3
  
  # API & Network
  dio: ^5.4.0
  
  # Charts & UI
  fl_chart: ^0.66.0
  table_calendar: ^3.1.0
  cupertino_icons: ^1.0.2

  flutter_vibrate: ^1.4.0
  
  # Utils
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/exercises.json
